configuration: {}
triggers:
  # Taglich um 15:30
  - id: "1"
    configuration:
      time: 15:30
    type: timer.TimeOfDayTrigger
conditions: []
actions:
  - inputs: {}
    id: "2"
    configuration:
      itemName: WeihnachtsbeleuchtungInnen
      command: ON
    type: core.ItemCommandAction
  - inputs: {}
    id: "3"
    configuration:
      itemName: WeihnachtsbeleuchtungAussen
      command: ON
    type: core.ItemCommandAction
